# Generated by Django 4.0.1 on 2022-01-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='datecomplited',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
